wandb_version: 1

IPC:
  desc: null
  value: null
LOG_DIR:
  desc: null
  value: ../logs
_wandb:
  desc: null
  value:
    cli_version: 0.10.17
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.10
    t:
      1:
      - 1
      2:
      - 1
      4: 3.6.10
      5: 0.10.17
      8:
      - 3
alpha:
  desc: null
  value: 32
bn_freeze:
  desc: null
  value: 1
dataset:
  desc: null
  value: cars
gpu_id:
  desc: null
  value: 0
l2_norm:
  desc: null
  value: 1
loss:
  desc: null
  value: Triplet
lr:
  desc: null
  value: 0.0001
lr_decay_gamma:
  desc: null
  value: 0.5
lr_decay_step:
  desc: null
  value: 20
model:
  desc: null
  value: googlenet
mrg:
  desc: null
  value: 0.1
nb_epochs:
  desc: null
  value: 60
nb_workers:
  desc: null
  value: 0
optimizer:
  desc: null
  value: adamw
remark:
  desc: null
  value: ''
sz_batch:
  desc: null
  value: 180
sz_embedding:
  desc: null
  value: 512
warm:
  desc: null
  value: 1
weight_decay:
  desc: null
  value: 0.0001
